apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    purpose: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "roboshop"
          effect: "PreferNoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - catalogue
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: catalogue
          image: 826334059644.dkr.ecr.us-east-1.amazonaws.com/roboshop-catalogue-demo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 200Mi
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/catalogue"



